// Parses GPX track files dropped into public/gpx/ and regenerates
// src/data/olleWaypoints.generated.ts, which olleCoursesData.ts merges in to
// override the straight-line approximation with the real trail geometry.
//
// Usage:
//   node scripts/import-gpx.mjs
//
// File naming (must match the `gpxFile` field already in olleCoursesData.ts):
//   course_01.gpx      -> course id 1
//   course_01_1.gpx    -> course id 1.1 (알트 코스)
//   course_18_2.gpx    -> course id 18.2
//
// Only courses whose GPX file exists get replaced; everything else keeps
// its current fallback waypoints, so partial drops (a few courses at a time)
// work fine.

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const GPX_DIR = path.join(__dirname, '..', 'public', 'gpx');
const OUT_FILE = path.join(__dirname, '..', 'src', 'data', 'olleWaypoints.generated.ts');

// Max distance (in degrees, roughly meters/111000) a point can deviate from
// the simplified line before it's kept — trims down raw GPS noise (often
// thousands of points at 1-5m spacing) to a size that renders smoothly.
const SIMPLIFY_EPSILON = 0.00007; // ~7-8m

function parseFileName(fileName) {
  const m = fileName.match(/^course_(\d{2})(?:_(\d))\.gpx$/) || fileName.match(/^course_(\d{2})\.gpx$/);
  if (!m) return null;
  const main = Number(m[1]);
  const sub = m[2] ? Number(m[2]) : 0;
  return sub ? Number((main + sub / 10).toFixed(1)) : main;
}

function parseGpx(xml) {
  const points = [];
  const re = /<trkpt\s+lat="(-?\d+(?:\.\d+)?)"\s+lon="(-?\d+(?:\.\d+)?)"/g;
  let match;
  while ((match = re.exec(xml))) {
    points.push({ lat: parseFloat(match[1]), lng: parseFloat(match[2]) });
  }
  if (points.length === 0) {
    // fall back to route points if this GPX has no track
    const reRte = /<rtept\s+lat="(-?\d+(?:\.\d+)?)"\s+lon="(-?\d+(?:\.\d+)?)"/g;
    while ((match = reRte.exec(xml))) {
      points.push({ lat: parseFloat(match[1]), lng: parseFloat(match[2]) });
    }
  }
  return points;
}

function perpendicularDistance(pt, a, b) {
  const [x, y] = [pt.lng, pt.lat];
  const [x1, y1] = [a.lng, a.lat];
  const [x2, y2] = [b.lng, b.lat];
  const dx = x2 - x1, dy = y2 - y1;
  if (dx === 0 && dy === 0) return Math.hypot(x - x1, y - y1);
  const t = ((x - x1) * dx + (y - y1) * dy) / (dx * dx + dy * dy);
  const clampedT = Math.max(0, Math.min(1, t));
  const px = x1 + clampedT * dx, py = y1 + clampedT * dy;
  return Math.hypot(x - px, y - py);
}

function douglasPeucker(points, epsilon) {
  if (points.length < 3) return points;
  let maxDist = 0, index = 0;
  const [first, last] = [points[0], points[points.length - 1]];
  for (let i = 1; i < points.length - 1; i++) {
    const d = perpendicularDistance(points[i], first, last);
    if (d > maxDist) { maxDist = d; index = i; }
  }
  if (maxDist > epsilon) {
    const left = douglasPeucker(points.slice(0, index + 1), epsilon);
    const right = douglasPeucker(points.slice(index), epsilon);
    return [...left.slice(0, -1), ...right];
  }
  return [first, last];
}

function main() {
  if (!existsSync(GPX_DIR)) {
    console.log(`public/gpx 폴더가 없어요. GPX 파일을 ${GPX_DIR} 에 course_01.gpx 형식으로 넣고 다시 실행하세요.`);
    writeFileSync(OUT_FILE, generateOutput({}));
    return;
  }

  const files = readdirSync(GPX_DIR).filter((f) => f.endsWith('.gpx'));
  if (files.length === 0) {
    console.log('public/gpx 폴더가 비어 있어요. GPX 파일을 넣고 다시 실행하세요.');
    writeFileSync(OUT_FILE, generateOutput({}));
    return;
  }

  const result = {};
  for (const file of files) {
    const id = parseFileName(file);
    if (id == null) {
      console.warn(`파일명을 코스 id로 해석 못함, 건너뜀: ${file}`);
      continue;
    }
    const xml = readFileSync(path.join(GPX_DIR, file), 'utf-8');
    const raw = parseGpx(xml);
    if (raw.length === 0) {
      console.warn(`트랙 포인트를 찾지 못함, 건너뜀: ${file}`);
      continue;
    }
    const simplified = douglasPeucker(raw, SIMPLIFY_EPSILON);
    result[id] = simplified;
    console.log(`${file} -> id ${id}: ${raw.length}개 포인트 -> ${simplified.length}개로 축약`);
  }

  writeFileSync(OUT_FILE, generateOutput(result));
  console.log(`\n${Object.keys(result).length}개 코스 반영: ${OUT_FILE}`);
}

function generateOutput(map) {
  const entries = Object.entries(map)
    .map(([id, pts]) => {
      const body = pts.map((p) => `{lat:${p.lat},lng:${p.lng}}`).join(',');
      return `  ${id}: [${body}],`;
    })
    .join('\n');
  return `// AUTO-GENERATED by scripts/import-gpx.mjs — do not edit by hand.
// Re-run \`node scripts/import-gpx.mjs\` after adding/updating files in public/gpx/.
import type { CourseWaypoint } from './olleCoursesData';

export const GPX_WAYPOINTS: Record<number, CourseWaypoint[]> = {
${entries}
};
`;
}

main();
