// AUTO-GENERATED by scripts/import-gpx.mjs — do not edit by hand.
// Re-run `node scripts/import-gpx.mjs` after adding/updating files in public/gpx/.
import type { CourseWaypoint } from './olleCoursesData';

export const GPX_WAYPOINTS: Record<number, CourseWaypoint[]> = {

};
